import type { TFunction } from "i18next";
import type { ContentFilterState } from "../../components/contentFilter.types";
import type { CourseItem, CourseStatus } from "../../components/courses/course.types";

export function getMockCourses(t: TFunction): CourseItem[] {
    return [
        {
            id: "react-architecture",
            title: t("dashboard.courses.mock.react_title"),
            description: t("dashboard.courses.mock.react_body"),
            category: t("dashboard.courses.mock.cat_code"),
            domain: "code",
            status: "published",
            pricing: "coins",
            lessons: 18,
            duration: "6h 20m",
            students: "4,280",
            studentsCount: 4280,
            completion: "76%",
            completionValue: 76,
            shorts: 14,
            topics: ["react", "architecture", "hooks"],
            createdAt: "2026-09-10",
        },
        {
            id: "figma-systems",
            title: t("dashboard.courses.mock.figma_title"),
            description: t("dashboard.courses.mock.figma_body"),
            category: t("dashboard.courses.mock.cat_ui"),
            domain: "ui-ux",
            status: "published",
            pricing: "premium",
            lessons: 12,
            duration: "4h 10m",
            students: "3,120",
            studentsCount: 3120,
            completion: "81%",
            completionValue: 81,
            shorts: 9,
            topics: ["figma", "systems", "autolayout"],
            createdAt: "2026-09-08",
        },
        {
            id: "python-zero",
            title: t("dashboard.courses.mock.python_title"),
            description: t("dashboard.courses.mock.python_body"),
            category: t("dashboard.courses.mock.cat_code"),
            domain: "code",
            status: "published",
            pricing: "free",
            lessons: 24,
            duration: "8h 05m",
            students: "8,640",
            studentsCount: 8640,
            completion: "69%",
            completionValue: 69,
            shorts: 21,
            topics: ["python", "loops", "fundamentals"],
            createdAt: "2026-09-04",
        },
        {
            id: "weeknight-cooking",
            title: t("dashboard.courses.mock.cooking_title"),
            description: t("dashboard.courses.mock.cooking_body"),
            category: t("dashboard.courses.mock.cat_cooking"),
            domain: "cooking",
            status: "published",
            pricing: "coins",
            lessons: 10,
            duration: "3h 40m",
            students: "2,190",
            studentsCount: 2190,
            completion: "84%",
            completionValue: 84,
            shorts: 11,
            topics: ["cooking", "weeknight", "pasta"],
            createdAt: "2026-09-06",
        },
        {
            id: "mobility-foundations",
            title: t("dashboard.courses.mock.mobility_title"),
            description: t("dashboard.courses.mock.mobility_body"),
            category: t("dashboard.courses.mock.cat_fitness"),
            domain: "fitness",
            status: "published",
            pricing: "free",
            lessons: 8,
            duration: "2h 15m",
            students: "1,870",
            studentsCount: 1870,
            completion: "88%",
            completionValue: 88,
            shorts: 7,
            topics: ["mobility", "warmup", "fitness"],
            createdAt: "2026-09-03",
        },
        {
            id: "brand-sprint",
            title: t("dashboard.courses.mock.brand_title"),
            description: t("dashboard.courses.mock.brand_body"),
            category: t("dashboard.courses.mock.cat_ui"),
            domain: "ui-ux",
            status: "published",
            pricing: "premium",
            lessons: 9,
            duration: "3h 25m",
            students: "960",
            studentsCount: 960,
            completion: "73%",
            completionValue: 73,
            shorts: 6,
            topics: ["brand", "color", "identity"],
            createdAt: "2026-08-28",
        },
        {
            id: "knife-path",
            title: t("dashboard.courses.mock.knife_title"),
            description: t("dashboard.courses.mock.knife_body"),
            category: t("dashboard.courses.mock.cat_cooking"),
            domain: "cooking",
            status: "published",
            pricing: "coins",
            lessons: 7,
            duration: "2h 50m",
            students: "1,540",
            studentsCount: 1540,
            completion: "79%",
            completionValue: 79,
            shorts: 8,
            topics: ["cooking", "knife", "skills"],
            createdAt: "2026-08-22",
        },
        {
            id: "dance-conditioning",
            title: t("dashboard.courses.mock.dance_title"),
            description: t("dashboard.courses.mock.dance_body"),
            category: t("dashboard.courses.mock.cat_fitness"),
            domain: "fitness",
            status: "published",
            pricing: "coins",
            lessons: 11,
            duration: "3h 55m",
            students: "2,410",
            studentsCount: 2410,
            completion: "82%",
            completionValue: 82,
            shorts: 13,
            topics: ["dance", "conditioning", "fitness"],
            createdAt: "2026-09-11",
        },
        {
            id: "css-studio",
            title: t("dashboard.courses.mock.css_title"),
            description: t("dashboard.courses.mock.css_body"),
            category: t("dashboard.courses.mock.cat_code"),
            domain: "code",
            status: "draft",
            pricing: "free",
            lessons: 6,
            duration: "1h 45m",
            students: "0",
            studentsCount: 0,
            completion: "—",
            completionValue: 0,
            shorts: 4,
            topics: ["css", "grid", "layout"],
            createdAt: "2026-09-13",
        },
        {
            id: "morning-series",
            title: t("dashboard.courses.mock.morning_title"),
            description: t("dashboard.courses.mock.morning_body"),
            category: t("dashboard.courses.mock.cat_fitness"),
            domain: "fitness",
            status: "draft",
            pricing: "coins",
            lessons: 5,
            duration: "1h 20m",
            students: "0",
            studentsCount: 0,
            completion: "—",
            completionValue: 0,
            shorts: 3,
            topics: ["morning", "mobility", "routine"],
            createdAt: "2026-09-12",
        },
        {
            id: "pasta-masterclass",
            title: t("dashboard.courses.mock.pasta_title"),
            description: t("dashboard.courses.mock.pasta_body"),
            category: t("dashboard.courses.mock.cat_cooking"),
            domain: "cooking",
            status: "review",
            pricing: "premium",
            lessons: 14,
            duration: "5h 10m",
            students: "0",
            studentsCount: 0,
            completion: "—",
            completionValue: 0,
            shorts: 10,
            topics: ["pasta", "sauce", "plating"],
            createdAt: "2026-09-09",
        },
        {
            id: "tokens-deep-dive",
            title: t("dashboard.courses.mock.tokens_title"),
            description: t("dashboard.courses.mock.tokens_body"),
            category: t("dashboard.courses.mock.cat_ui"),
            domain: "ui-ux",
            status: "review",
            pricing: "coins",
            lessons: 8,
            duration: "2h 35m",
            students: "0",
            studentsCount: 0,
            completion: "—",
            completionValue: 0,
            shorts: 5,
            topics: ["tokens", "theme", "design"],
            createdAt: "2026-09-07",
        },
    ];
}

export function countCoursesByStatus(items: CourseItem[]): Record<CourseStatus | "all", number> {
    return items.reduce(
        (acc, item) => {
            acc.all += 1;
            acc[item.status] += 1;
            return acc;
        },
        { all: 0, published: 0, draft: 0, review: 0 },
    );
}

export function filterCourses(items: CourseItem[], filter: ContentFilterState): CourseItem[] {
    const query = filter.query.trim().toLowerCase();

    const next = items.filter((item) => {
        const matchesDomain = filter.domain === "all" || item.domain === filter.domain;
        const matchesStatus = filter.status === "all" || item.status === filter.status;
        const matchesTier = filter.tier === "all" || item.pricing === filter.tier;
        const haystack = [item.title, item.description, item.category, ...item.topics].join(" ").toLowerCase();
        const matchesQuery = !query || haystack.includes(query);
        return matchesDomain && matchesStatus && matchesTier && matchesQuery;
    });

    return [...next].sort((a, b) => {
        if (filter.sort === "recent") return b.createdAt.localeCompare(a.createdAt);
        if (filter.sort === "completion") return b.completionValue - a.completionValue;
        if (filter.sort === "lessons") return b.lessons - a.lessons;
        return b.studentsCount - a.studentsCount;
    });
}
